version: '2.2'

services:
  libreread:
    build: .
    environment:
      - "LIBREREAD_REDIS_PATH=redis:6379"
      - "LIBREREAD_DOMAIN_ADDRESS=${LIBREREAD_DOMAIN_ADDRESS}"
      - "LIBREREAD_SMTP_SERVER=${LIBREREAD_SMTP_SERVER}"
      - "LIBREREAD_SMTP_PORT=${LIBREREAD_SMTP_PORT}"
      - "LIBREREAD_SMTP_ADDRESS=${LIBREREAD_SMTP_ADDRESS}"
      - "LIBREREAD_SMTP_PASSWORD=${LIBREREAD_SMTP_PASSWORD}"
    ports:
      - "8080:8080"
    volumes:
      - ./libreread-data:/libreread
  redis:
    image: redis
    volumes:
      - ./redis-data:/libreread-redis