# Copyright 2017 Nirmal Kumar

# This file is part of LibreRead.

# LibreRead is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# LibreRead is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with LibreRead.  If not, see <http://www.gnu.org/licenses/>.

version: '2.2'

services:
  libreread:
    environment:
      - "LIBREREAD_ES_PATH=http://elasticsearch:9200"
      - "LIBREREAD_ELASTICSEARCH=1"
    depends_on:
      - elasticsearch
  elasticsearch:
    build:
      context: elasticsearch/
    container_name: elasticsearch
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx1g -Xms1g"
  wait:
    image: waisbrot/wait
    links:
      - elasticsearch
    environment:
      - TARGETS=elasticsearch:9200