# Copyright 2017 Nirmal Kumar

# This file is part of LibreRead.

# LibreRead is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# LibreRead is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with LibreRead.  If not, see <http://www.gnu.org/licenses/>.

version: '2.2'

services:
  libreread:
    build: .
    environment:
      - "LIBREREAD_REDIS_PATH=redis:6379"
      - "LIBREREAD_DOMAIN_ADDRESS=${LIBREREAD_DOMAIN_ADDRESS}"
      - "LIBREREAD_SMTP_SERVER=${LIBREREAD_SMTP_SERVER}"
      - "LIBREREAD_SMTP_PORT=${LIBREREAD_SMTP_PORT}"
      - "LIBREREAD_SMTP_ADDRESS=${LIBREREAD_SMTP_ADDRESS}"
      - "LIBREREAD_SMTP_PASSWORD=${LIBREREAD_SMTP_PASSWORD}"
    ports:
      - "8080:8080"
    volumes:
      - ./libreread-data:/libreread
  redis:
    image: redis
    volumes:
      - ./redis-data:/libreread-redis